services:
  api:
    image: serversideup/php:8.4-fpm-alpine
    user: "${UID-1000}:${GID-1000}"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: [ "php", "/var/www/html/artisan", "serve", "--host=0.0.0.0" ]
    healthcheck:
      test: curl --fail http://localhost:8000/up || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
      
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      start_period: 30s
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - phpmyadmindata:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysqldata:
  phpmyadmindata: